-- Baraka CRM schema restored from application source
create extension if not exists pgcrypto;
create table public.tenants (id uuid primary key default gen_random_uuid(), name text not null, created_at timestamptz not null default now());
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, tenant_id uuid not null references public.tenants(id) on delete cascade, full_name text not null, role text not null default 'user' check (role in ('admin','manager','user')), created_at timestamptz not null default now());
create table public.clients (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, full_name text not null, phone text, address text, created_at timestamptz not null default now());
create table public.investors (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, full_name text not null, phone text, total_capital numeric(14,2) not null default 0 check (total_capital >= 0), created_at timestamptz not null default now());
create table public.contracts (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, client_id uuid not null references public.clients(id) on delete restrict, item_description text not null, cost_price numeric(14,2) not null check (cost_price >= 0), sale_price numeric(14,2) not null check (sale_price >= 0), markup numeric(14,2) generated always as (sale_price-cost_price) stored, down_payment numeric(14,2) not null default 0 check (down_payment >= 0), term_months integer not null check (term_months > 0), payment_day integer not null default 1 check (payment_day between 1 and 28), status text not null default 'active' check (status in ('active','overdue','closed')), created_at timestamptz not null default now());
create table public.contract_funding (id uuid primary key default gen_random_uuid(), contract_id uuid not null references public.contracts(id) on delete cascade, investor_id uuid not null references public.investors(id) on delete restrict, amount numeric(14,2) not null check (amount > 0), share_pct numeric(7,2) not null default 0 check (share_pct between 0 and 100), created_at timestamptz not null default now());
create table public.guarantors (id uuid primary key default gen_random_uuid(), contract_id uuid not null references public.contracts(id) on delete cascade, full_name text not null, phone text, address text, notes text, created_at timestamptz not null default now());
create table public.payment_schedule (id uuid primary key default gen_random_uuid(), contract_id uuid not null references public.contracts(id) on delete cascade, installment_no integer not null check (installment_no > 0), due_date date not null, amount_due numeric(14,2) not null check (amount_due >= 0), created_at timestamptz not null default now(), unique(contract_id, installment_no));
create table public.payments (id uuid primary key default gen_random_uuid(), contract_id uuid not null references public.contracts(id) on delete cascade, amount numeric(14,2) not null check (amount > 0), received_by uuid references public.profiles(id) on delete set null, paid_at date not null default current_date, created_at timestamptz not null default now());
create table public.investor_payouts (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, investor_id uuid not null references public.investors(id) on delete restrict, amount numeric(14,2) not null check (amount > 0), note text, paid_at date not null default current_date, created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now());
create table public.cash_operations (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, type text not null check (type in ('in','out','initial')), amount numeric(14,2) not null check (amount >= 0), category text not null, description text, operation_date date not null default current_date, created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now());
create table public.expenses (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, amount numeric(14,2) not null check (amount >= 0), category text not null, description text, expense_date date not null default current_date, created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now());
create index profiles_tenant_id_idx on public.profiles(tenant_id);
create index clients_tenant_id_idx on public.clients(tenant_id);
create index investors_tenant_id_idx on public.investors(tenant_id);
create index contracts_tenant_id_created_at_idx on public.contracts(tenant_id,created_at desc);
create index contracts_client_id_idx on public.contracts(client_id);
create index contract_funding_contract_id_idx on public.contract_funding(contract_id);
create index contract_funding_investor_id_idx on public.contract_funding(investor_id);
create index guarantors_contract_id_idx on public.guarantors(contract_id);
create index payment_schedule_contract_id_due_date_idx on public.payment_schedule(contract_id,due_date);
create index payments_contract_id_paid_at_idx on public.payments(contract_id,paid_at);
create index payments_received_by_idx on public.payments(received_by);
create index investor_payouts_tenant_id_paid_at_idx on public.investor_payouts(tenant_id,paid_at desc);
create index investor_payouts_investor_id_idx on public.investor_payouts(investor_id);
create index cash_operations_tenant_id_operation_date_idx on public.cash_operations(tenant_id,operation_date desc);
create index expenses_tenant_id_expense_date_idx on public.expenses(tenant_id,expense_date desc);
create index expenses_created_by_idx on public.expenses(created_by);
alter table public.tenants enable row level security;
alter table public.profiles enable row level security;
alter table public.clients enable row level security;
alter table public.investors enable row level security;
alter table public.contracts enable row level security;
alter table public.contract_funding enable row level security;
alter table public.guarantors enable row level security;
alter table public.payment_schedule enable row level security;
alter table public.payments enable row level security;
alter table public.investor_payouts enable row level security;
alter table public.cash_operations enable row level security;
alter table public.expenses enable row level security;
create policy tenants_select_member on public.tenants for select to authenticated using (id=(select p.tenant_id from public.profiles p where p.id=(select auth.uid())));
create policy tenants_insert_authenticated on public.tenants for insert to authenticated with check (true);
create policy profiles_select_self on public.profiles for select to authenticated using (id=(select auth.uid()));
create policy profiles_insert_self on public.profiles for insert to authenticated with check (id=(select auth.uid()));
create policy profiles_update_self on public.profiles for update to authenticated using (id=(select auth.uid())) with check (id=(select auth.uid()));
create policy clients_tenant_all on public.clients for all to authenticated using (tenant_id=(select p.tenant_id from public.profiles p where p.id=(select auth.uid()))) with check (tenant_id=(select p.tenant_id from public.profiles p where p.id=(select auth.uid())));
create policy investors_tenant_all on public.investors for all to authenticated using (tenant_id=(select p.tenant_id from public.profiles p where p.id=(select auth.uid()))) with check (tenant_id=(select p.tenant_id from public.profiles p where p.id=(select auth.uid())));
create policy contracts_tenant_all on public.contracts for all to authenticated using (tenant_id=(select p.tenant_id from public.profiles p where p.id=(select auth.uid()))) with check (tenant_id=(select p.tenant_id from public.profiles p where p.id=(select auth.uid())));
create policy funding_tenant_all on public.contract_funding for all to authenticated using (exists(select 1 from public.contracts c join public.profiles p on p.tenant_id=c.tenant_id where c.id=contract_id and p.id=(select auth.uid()))) with check (exists(select 1 from public.contracts c join public.profiles p on p.tenant_id=c.tenant_id where c.id=contract_id and p.id=(select auth.uid())));
create policy guarantors_tenant_all on public.guarantors for all to authenticated using (exists(select 1 from public.contracts c join public.profiles p on p.tenant_id=c.tenant_id where c.id=contract_id and p.id=(select auth.uid()))) with check (exists(select 1 from public.contracts c join public.profiles p on p.tenant_id=c.tenant_id where c.id=contract_id and p.id=(select auth.uid())));
create policy schedule_tenant_all on public.payment_schedule for all to authenticated using (exists(select 1 from public.contracts c join public.profiles p on p.tenant_id=c.tenant_id where c.id=contract_id and p.id=(select auth.uid()))) with check (exists(select 1 from public.contracts c join public.profiles p on p.tenant_id=c.tenant_id where c.id=contract_id and p.id=(select auth.uid())));
create policy payments_tenant_all on public.payments for all to authenticated using (exists(select 1 from public.contracts c join public.profiles p on p.tenant_id=c.tenant_id where c.id=contract_id and p.id=(select auth.uid()))) with check (exists(select 1 from public.contracts c join public.profiles p on p.tenant_id=c.tenant_id where c.id=contract_id and p.id=(select auth.uid())));
create policy payouts_tenant_all on public.investor_payouts for all to authenticated using (tenant_id=(select p.tenant_id from public.profiles p where p.id=(select auth.uid()))) with check (tenant_id=(select p.tenant_id from public.profiles p where p.id=(select auth.uid())) and exists(select 1 from public.investors i where i.id=investor_id and i.tenant_id=tenant_id));
create policy cash_tenant_all on public.cash_operations for all to authenticated using (tenant_id=(select p.tenant_id from public.profiles p where p.id=(select auth.uid()))) with check (tenant_id=(select p.tenant_id from public.profiles p where p.id=(select auth.uid())));
create policy expenses_tenant_all on public.expenses for all to authenticated using (tenant_id=(select p.tenant_id from public.profiles p where p.id=(select auth.uid()))) with check (tenant_id=(select p.tenant_id from public.profiles p where p.id=(select auth.uid())));
grant select,insert,update,delete on all tables in schema public to authenticated;
